# Generated by Django 6.0.3 on 2026-03-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FurnitureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('price_type', models.CharField(choices=[('unit', 'Per Unit'), ('sqft', 'Per Sq Ft')], default='unit', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compatible_packages', models.JSONField(blank=True, default=list)),
                ('is_ready_made', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InteriorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=24, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rate_per_sqft', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('base_timeline_weeks', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rate_per_sqft'],
            },
        ),
        migrations.CreateModel(
            name='LocationMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=120, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='RenovationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('price_type', models.CharField(choices=[('unit', 'Per Unit'), ('sqft', 'Per Sq Ft')], default='sqft', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('enabled_for_project_types', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EstimateLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('office', 'Office')], max_length=24)),
                ('project_type', models.CharField(choices=[('new', 'New Interior'), ('renovation', 'Renovation')], max_length=24)),
                ('area_sqft', models.PositiveIntegerField()),
                ('room_count', models.PositiveIntegerField(default=1)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('estimate_snapshot', models.JSONField(blank=True, default=dict)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='api.interiorpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
